#!/usr/bin/env python3
"""S41 cycle-04: actual-law averaged localization of the complete curvature jet.

This file accompanies S41_CYCLE04_RESULT.md.  It contains:

* exact finite actual-sine atom enumeration for a length-N interval, averaged
  over all N possible anchor positions;
* the complete moving-law second derivative
    w'' phi + 2 w' phi' q' + w[phi''(q')^2 + phi' q''];
* the equivalent finite V14 flip-kernel and a self-test of their equality;
* posterior-projection / Schur-data dictionary checks;
* projection-flow boundary-energy checks;
* the explicit cycle-04 O_c(sqrt(log N / N)) observation bound;
* the exact finite response-coordinate loss, kept separate from observation
  localization.

The enumerations and quadrature use ordinary double precision.  They are
reproducibility diagnostics, not interval-arithmetic sign certificates.
"""
from __future__ import annotations

import argparse
import itertools
import math
from dataclasses import dataclass
from typing import Iterable, Sequence

import numpy as np


def q_sine(i: int, j: int) -> float:
    if i == j:
        return 0.5
    k = i - j
    return math.sin(math.pi * k / 2.0) / (math.pi * k)


def phi(q: float) -> float:
    return (q - 0.5) * math.log(q / (1.0 - q))


def phi_prime(q: float) -> float:
    return math.log(q / (1.0 - q)) + (q - 0.5) / (q * (1.0 - q))


def phi_second(q: float) -> float:
    return 1.0 / (2.0 * q * q * (1.0 - q) ** 2)


def breg_phi(x: float, y: float) -> float:
    return phi(x) - phi(y) - phi_prime(y) * (x - y)


def breg_phi_prime(x: float, y: float) -> float:
    # Bregman divergence generated by phi'.
    return phi_prime(x) - phi_prime(y) - phi_second(y) * (x - y)


@dataclass(frozen=True)
class WordData:
    sites: tuple[int, ...]
    anchor: int
    external: tuple[int, ...]
    bits: tuple[int, ...]
    B: np.ndarray
    b: np.ndarray
    G: np.ndarray
    v: np.ndarray
    q: float
    r: float
    weight: float


def word_data(sites: Sequence[int], anchor: int, bits: Sequence[int], x: float) -> WordData:
    sites = tuple(int(s) for s in sites)
    external = tuple(s for s in sites if s != anchor)
    bits = tuple(int(b) for b in bits)
    if len(bits) != len(external):
        raise ValueError("bits must have one entry per observed/external site")
    n = len(external)
    B = np.empty((n, n), dtype=float)
    bvec = np.empty(n, dtype=float)
    for a, i in enumerate(external):
        bvec[a] = x * q_sine(i, anchor)
        for bb, j in enumerate(external):
            if i == j:
                B[a, bb] = 0.5 if bits[a] else -0.5
            else:
                B[a, bb] = x * q_sine(i, j)
    if n:
        G = np.linalg.inv(B)
        v = G @ bvec
        r = float(bvec @ v)
        qpost = 0.5 - r
        sign_det, logabs = np.linalg.slogdet(B)
        prefactor = -1.0 if ((n - sum(bits)) & 1) else 1.0
        weight = prefactor * float(sign_det) * math.exp(float(logabs))
    else:
        G = np.empty((0, 0), dtype=float)
        v = np.empty(0, dtype=float)
        r = 0.0
        qpost = 0.5
        weight = 1.0
    return WordData(
        sites=sites,
        anchor=anchor,
        external=external,
        bits=bits,
        B=B,
        b=bvec,
        G=G,
        v=v,
        q=qpost,
        r=r,
        weight=weight,
    )


def flip_bits(bits: Sequence[int], j: int) -> tuple[int, ...]:
    out = list(bits)
    out[j] = 1 - out[j]
    return tuple(out)


def finite_v14_kernel(sites: Sequence[int], anchor: int, bits: Sequence[int], x: float) -> float:
    """Exact finite complete curvature kernel (the V14 grouped formula)."""
    base = word_data(sites, anchor, bits, x)
    n = len(base.external)
    q = base.q
    G = base.G
    v = base.v
    A = 1.0 + float(v @ v)

    flipped: list[WordData] = [
        word_data(sites, anchor, flip_bits(bits, j), x) for j in range(n)
    ]

    def B_phi(bits_local: Sequence[int], data_local: WordData) -> float:
        total = 0.0
        for i in range(n):
            sigma = 2 * int(bits_local[i]) - 1
            rbar = sigma - float(data_local.G[i, i])
            data_i = word_data(sites, anchor, flip_bits(bits_local, i), x)
            total += rbar * breg_phi(data_i.q, data_local.q)
        return total

    base_B = B_phi(bits, base)
    ans = phi_second(q)
    G2 = G @ G
    for j in range(n):
        sigma = 2 * int(bits[j]) - 1
        rbar = sigma - float(G[j, j])
        dj = flipped[j].q - q
        Aj = 1.0 + float(flipped[j].v @ flipped[j].v)
        ans += rbar * breg_phi_prime(flipped[j].q, q)
        ans += float(G2[j, j]) * breg_phi(flipped[j].q, q)
        ans += rbar * (
            (phi_prime(flipped[j].q) - phi_prime(q)) * Aj
            - phi_second(q) * dj * A
        )
        ans += rbar * (B_phi(flip_bits(bits, j), flipped[j]) - base_B)
    return float(ans)


@dataclass(frozen=True)
class FinitePoint:
    F_second: float
    V14_expectation: float
    response_loss: float
    probability_sum: float
    min_probability: float


def finite_point(
    sites: Sequence[int],
    anchor: int,
    x: float,
    retained_sites: set[int] | None = None,
    check_v14: bool = False,
) -> FinitePoint:
    """Enumerate the exact finite second derivative at one x.

    retained_sites controls only the separately-accounted response-coordinate
    loss.  If None, all finite response coordinates are retained and that loss
    is zero.
    """
    external = tuple(s for s in sites if s != anchor)
    n = len(external)
    f2 = 0.0
    v14 = 0.0
    loss = 0.0
    psum = 0.0
    pmin = float("inf")
    for bits in itertools.product((0, 1), repeat=n):
        data = word_data(sites, anchor, bits, x)
        w = data.weight
        if w < -2e-10:
            raise ArithmeticError(f"negative atom {w}; use higher precision")
        w = max(0.0, w)
        psum += w
        pmin = min(pmin, w)
        G = data.G
        b = data.b
        q = data.q
        if n:
            trG = float(np.trace(G))
            G2 = G @ G
            q1 = 1.0 + float(b @ G2 @ b)
            q2 = -2.0 * float(b @ (G2 @ G) @ b)
            w1 = w * trG
            w2 = w * (trG * trG - float(np.trace(G2)))
        else:
            q1, q2, w1, w2 = 1.0, 0.0, 0.0, 0.0
        f2 += (
            w2 * phi(q)
            + 2.0 * w1 * phi_prime(q) * q1
            + w * (phi_second(q) * q1 * q1 + phi_prime(q) * q2)
        )
        if check_v14:
            v14 += w * finite_v14_kernel(sites, anchor, bits, x)
        if retained_sites is not None:
            tau = sum(
                float(abs(data.v[k]) ** 2)
                for k, site in enumerate(external)
                if site not in retained_sites
            )
            loss += 8.0 * w * tau * tau / (1.0 - 4.0 * data.r * data.r) ** 2
    return FinitePoint(
        F_second=float(f2),
        V14_expectation=float(v14) if check_v14 else float("nan"),
        response_loss=float(loss),
        probability_sum=float(psum),
        min_probability=float(pmin),
    )


def averaged_finite_point(N: int, x: float, check_v14: bool = False) -> tuple[float, float, float]:
    """Average over every anchor in the actual sine principal interval [0,N)."""
    if N < 1:
        raise ValueError("N must be positive")
    sites = tuple(range(N))
    vals = []
    kernel_vals = []
    max_psum_error = 0.0
    for anchor in sites:
        fp = finite_point(sites, anchor, x, retained_sites=None, check_v14=check_v14)
        vals.append(fp.F_second)
        if check_v14:
            kernel_vals.append(fp.V14_expectation)
        max_psum_error = max(max_psum_error, abs(fp.probability_sum - 1.0))
    v14_avg = float(np.mean(kernel_vals)) if check_v14 else float("nan")
    return float(np.mean(vals)), v14_avg, max_psum_error


def averaged_gamma(N: int, c: float, nodes: int = 20) -> tuple[float, float]:
    """Gauss-Legendre diagnostic for Gamma_N^av(c)."""
    if not (0.0 < c < 1.0):
        raise ValueError("require 0<c<1")
    xs, ws = np.polynomial.legendre.leggauss(nodes)
    gamma = 0.0
    max_psum_error = 0.0
    for t, wt in zip(xs, ws):
        u = 0.5 * (float(t) + 1.0)
        weight = 0.5 * float(wt)
        f2, _, err = averaged_finite_point(N, c * u, check_v14=False)
        gamma += weight * u * f2
        max_psum_error = max(max_psum_error, err)
    return gamma, max_psum_error


def sine_number_variance(N: int) -> float:
    """Exact half-filled sine number variance, numerically evaluated."""
    if N < 1:
        raise ValueError("N must be positive")
    head = sum(1.0 / k for k in range(1, N + 1, 2))
    try:
        import mpmath as mp
        first = N + 1
        if first % 2 == 0:
            first += 1
        tail = float(mp.polygamma(1, first / 2.0) / 4.0)
    except Exception:
        cutoff = N + 500000
        tail = sum(1.0 / (k * k) for k in range(N + 1, cutoff) if k & 1)
        tail += 1.0 / cutoff
    return 2.0 / math.pi**2 * (head + N * tail)


def jet_constant(c: float) -> float:
    """Conservative explicit constant from the complete-jet tally."""
    if not (0.0 < c < 1.0):
        raise ValueError("require 0<c<1")
    a = 2.0 / (1.0 - c)
    return 2.0**28 * a**28


@dataclass(frozen=True)
class AveragedObservationBound:
    c: float
    N: int
    variance: float
    a: float
    s: float
    Cjet: float
    tail_term: float
    transport_term: float
    split_gamma_error: float
    simple_gamma_error: float
    gamma_error: float


def averaged_observation_bound(c: float, N: int) -> AveragedObservationBound:
    """Cycle-04 effective complete-jet observation error.

    The pointwise-x averaged comparison is bounded by
      2 C s^7 V/N + (4/3) C s^2(s^(3/2)-1) sqrt(V/N).
    Monotonicity in x<=c and int_0^1 u du=1/2 give the two terms below for
    |Gamma(c)-Gamma_N^av(c)|.
    """
    if not (0.0 < c < 1.0):
        raise ValueError("require 0<c<1")
    if N < 1:
        raise ValueError("N must be positive")
    V = sine_number_variance(N)
    a = 2.0 / (1.0 - c)
    s = math.sqrt((1.0 + c) / (1.0 - c))
    C = jet_constant(c)
    tail = C * s**7 * V / N
    transport = (2.0 / 3.0) * C * s**2 * (s**1.5 - 1.0) * math.sqrt(V / N)
    simple = (5.0 / 3.0) * C * s**3.5 * math.sqrt(V / N)
    return AveragedObservationBound(
        c=c,
        N=N,
        variance=V,
        a=a,
        s=s,
        Cjet=C,
        tail_term=tail,
        transport_term=transport,
        split_gamma_error=tail + transport,
        simple_gamma_error=simple,
        gamma_error=min(tail + transport, simple),
    )


def block_half_projection(m: int, seed: int = 1) -> np.ndarray:
    """A real rank-m projection on 2m sites with every diagonal equal to 1/2."""
    rng = np.random.default_rng(seed)
    X = rng.normal(size=(m, m))
    U, _ = np.linalg.qr(X)
    top = np.concatenate([np.eye(m), U], axis=1)
    # P = 1/2 [[I,U],[U^T,I]] is a rank-m orthogonal projection.
    return 0.5 * np.block([[np.eye(m), U], [U.T, np.eye(m)]])


def posterior_projection(Q: np.ndarray, observed: Sequence[int], signs: Sequence[int], x: float) -> np.ndarray:
    """Projection posterior after BSC outputs on the selected coordinates."""
    n = Q.shape[0]
    vals, vecs = np.linalg.eigh(Q)
    U = vecs[:, vals > 0.5]
    s = math.sqrt((1.0 + x) / (1.0 - x))
    d = np.ones(n)
    for j, y in zip(observed, signs):
        d[int(j)] = s ** int(y)
    DU = d[:, None] * U
    middle = U.T @ ((d * d)[:, None] * U)
    return DU @ np.linalg.inv(middle) @ DU.T


def dictionary_check(x: float = 0.7, seed: int = 1) -> tuple[float, float, float]:
    """Check the posterior-projection / Schur-data dictionary numerically."""
    Q = block_half_projection(4, seed)
    n = Q.shape[0]
    anchor = 0
    observed = list(range(1, n))
    signs = [1 if (j % 3) else -1 for j in observed]
    bits = [(y + 1) // 2 for y in signs]
    S = np.diag(signs)
    B = np.empty((n - 1, n - 1))
    b = x * Q[np.ix_(observed, [anchor])].ravel()
    for aa, i in enumerate(observed):
        for bb, j in enumerate(observed):
            if i == j:
                B[aa, bb] = 0.5 * signs[aa]
            else:
                B[aa, bb] = x * Q[i, j]
    G = np.linalg.inv(B)
    v = G @ b
    q = 0.5 - float(b @ v)
    P = posterior_projection(Q, observed, signs, x)
    lam = 2.0 * x / math.sqrt(1.0 - x * x)
    v_pred = lam * np.asarray(signs) * P[observed, anchor]
    Pj = P[np.ix_(observed, observed)]
    G_pred = 2.0 / (1.0 - x * x) * (
        S - x * S @ (2.0 * Pj - np.eye(n - 1)) @ S
    )
    q_pred = 0.5 + x * (P[anchor, anchor] - 0.5)
    return (
        abs(q - q_pred),
        float(np.max(np.abs(v - v_pred))),
        float(np.max(np.abs(G - G_pred))),
    )


def projection_from_tilt(Q: np.ndarray, d: np.ndarray) -> np.ndarray:
    vals, vecs = np.linalg.eigh(Q)
    U = vecs[:, vals > 0.5]
    DU = d[:, None] * U
    M = U.T @ ((d * d)[:, None] * U)
    return DU @ np.linalg.inv(M) @ DU.T


def boundary_energy(P: np.ndarray, interval: Sequence[int], anchor: int) -> tuple[float, float, float]:
    I = set(int(i) for i in interval)
    O = [i for i in range(P.shape[0]) if i not in I]
    J = [i for i in I if i != anchor]
    T_anchor = float(np.sum(np.abs(P[O, anchor]) ** 2))
    W = 0.0
    for j in J:
        Tj = float(np.sum(np.abs(P[O, j]) ** 2))
        W += abs(P[j, anchor]) ** 2 * Tj
    return T_anchor, W, T_anchor + W


def flow_check(x: float = 0.7, seed: int = 3) -> dict[str, float]:
    """Numerically check the outside-flow and one-site update inequalities."""
    Q = block_half_projection(5, seed)
    n = Q.shape[0]
    I = list(range(6))
    anchor = 2
    O = [i for i in range(n) if i not in I]
    s = math.sqrt((1.0 + x) / (1.0 - x))
    h = math.log(s)
    rng = np.random.default_rng(seed + 10)
    d0 = np.ones(n)
    # Finite observation inside I except the anchor.
    for j in I:
        if j != anchor:
            d0[j] = s ** (1 if rng.random() > 0.5 else -1)
    P0 = projection_from_tilt(Q, d0)
    U0 = boundary_energy(P0, I, anchor)[2]
    # Reveal outside observations.
    d1 = d0.copy()
    for j in O:
        d1[j] = s ** (1 if rng.random() > 0.5 else -1)
    P1 = projection_from_tilt(Q, d1)
    U1 = boundary_energy(P1, I, anchor)[2]
    column_change = float(np.linalg.norm(P1[:, anchor] - P0[:, anchor]))
    T0 = boundary_energy(P0, I, anchor)[0]
    outside_ratio = U1 / U0 if U0 > 0 else 0.0
    column_ratio = column_change / math.sqrt(T0) if T0 > 0 else 0.0

    # Observe the anchor itself; compare U^- and U^+.
    dplus = d0.copy()
    dplus[anchor] = s
    Pplus = projection_from_tilt(Q, dplus)
    Uplus = boundary_energy(Pplus, I, anchor)[2]
    center_ratio = U0 / Uplus if Uplus > 0 else 0.0
    return {
        "outside_U_ratio": outside_ratio,
        "outside_U_bound": s**3,
        "column_ratio": column_ratio,
        "column_bound": s - 1.0,
        "center_U_ratio": center_ratio,
        "center_U_bound": s**4,
    }


def run_self_tests() -> None:
    # Complete direct derivative = complete grouped V14 kernel.
    for N in range(2, 6):
        sites = tuple(range(N))
        anchor = N // 2
        fp = finite_point(sites, anchor, 0.7, check_v14=True)
        assert abs(fp.F_second - fp.V14_expectation) < 2e-10
        assert abs(fp.probability_sum - 1.0) < 2e-11
    qerr, verr, Gerr = dictionary_check()
    assert qerr < 2e-12 and verr < 2e-12 and Gerr < 3e-11
    flow = flow_check()
    assert flow["outside_U_ratio"] <= flow["outside_U_bound"] * (1.0 + 1e-9)
    assert flow["column_ratio"] <= flow["column_bound"] * (1.0 + 1e-9)
    assert flow["center_U_ratio"] <= flow["center_U_bound"] * (1.0 + 1e-9)
    for N in (1, 2, 5, 20):
        V = sine_number_variance(N)
        assert V <= (math.log(N) + 4.0) / math.pi**2 + 1e-12
    print("S41_CYCLE04 self-tests passed")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--c", type=float, default=0.95)
    parser.add_argument("--N", type=int, default=6)
    parser.add_argument("--quad-nodes", type=int, default=18)
    parser.add_argument("--enumerate", action="store_true")
    parser.add_argument("--check-v14", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        run_self_tests()

    bound = averaged_observation_bound(args.c, args.N)
    print("S41 cycle-04 averaged complete-jet observation bound")
    print(f"c={args.c:.17g}, N={args.N}")
    print(f"V_Q(N)={bound.variance:.12e}")
    print(f"a_c={bound.a:.12e}, s_c={bound.s:.12e}")
    print(f"C_jet(c)={bound.Cjet:.12e}")
    print(f"integrated tail term={bound.tail_term:.12e}")
    print(f"integrated transport term={bound.transport_term:.12e}")
    print(f"split E_av(c,N)={bound.split_gamma_error:.12e}")
    print(f"simple E_av(c,N)={bound.simple_gamma_error:.12e}")
    print(f"effective E_av(c,N)={bound.gamma_error:.12e}")

    qerr, verr, Gerr = dictionary_check(args.c if args.c < 0.98 else 0.7)
    print("\nPosterior-projection dictionary diagnostic")
    print(f"q error={qerr:.3e}, v error={verr:.3e}, G error={Gerr:.3e}")
    print("\nProjection-flow diagnostic")
    for key, value in flow_check(args.c if args.c < 0.98 else 0.7).items():
        print(f"{key}={value:.12e}")

    if args.check_v14:
        f2, k2, err = averaged_finite_point(args.N, min(args.c, 0.8), check_v14=True)
        print("\nComplete moving-law derivative / V14 equality diagnostic")
        print(f"direct averaged F''={f2:.15g}")
        print(f"V14 averaged expectation={k2:.15g}")
        print(f"difference={abs(f2-k2):.3e}")
        print(f"max atom normalization error={err:.3e}")

    if args.enumerate:
        if args.N > 10:
            raise ValueError("enumeration is exponential; use N<=10")
        gamma, err = averaged_gamma(args.N, args.c, args.quad_nodes)
        print("\nActual-sine averaged finite observation diagnostic")
        print(f"Gamma_N^av({args.c:.17g})={gamma:.15g}")
        print(f"max atom normalization error={err:.3e}")
        print("This is floating point, not an interval sign certificate.")
        print(f"rigorous analytic error bound={bound.gamma_error:.12e}")
        if gamma - bound.gamma_error > 0.0:
            print("The floating-point center minus analytic error is positive, but rounding is unpaid.")
        else:
            print("No positivity certificate at this N: the analytic remainder dominates.")


if __name__ == "__main__":
    main()
