"""Independent finite probes for the Claude/Fable Cycle16 audit.

All printed numerical values are generated by this script.  They are probes,
not interval certificates or proofs for arbitrary n.
"""

import math

import numpy as np


def sine_toeplitz(n: int, rho: float) -> np.ndarray:
    indices = np.arange(n)
    differences = indices[:, None] - indices[None, :]
    matrix = np.empty((n, n), dtype=float)
    matrix[differences == 0] = rho
    nonzero = differences != 0
    matrix[nonzero] = np.sin(np.pi * rho * differences[nonzero]) / (
        np.pi * differences[nonzero]
    )
    return matrix


def dpp_entropy_stats(kernel: np.ndarray) -> dict[str, float]:
    """Return H, H'', observed Fisher J, and the acceleration contribution."""
    n = len(kernel)
    entropy = 0.0
    hessian = 0.0
    fisher = 0.0
    acceleration = 0.0
    mass = 0.0
    first_mass_derivative = 0.0
    second_mass_derivative = 0.0

    for word in range(1 << n):
        bits = (word >> np.arange(n)) & 1
        masked = kernel - np.diag(1 - bits)
        sign = -1.0 if ((n - int(bits.sum())) & 1) else 1.0
        raw_probability = sign * np.linalg.det(masked)
        assert abs(np.imag(raw_probability)) < 1e-9
        probability = float(np.real(raw_probability))
        inverse = np.linalg.inv(masked)
        trace = np.trace(inverse)
        first = float(np.real(probability * trace))
        second = float(
            np.real(
                probability * (trace * trace - np.trace(inverse @ inverse))
            )
        )

        entropy -= probability * math.log(probability)
        fisher += first * first / probability
        acceleration += second * math.log(probability)
        mass += probability
        first_mass_derivative += first
        second_mass_derivative += second

    hessian = -fisher - acceleration
    assert abs(mass - 1.0) < 3e-8
    assert abs(first_mass_derivative) < 3e-6
    assert abs(second_mass_derivative) < 3e-5
    return {
        "H": entropy,
        "H2": hessian,
        "F": -hessian,
        "J": fisher,
        "acceleration": acceleration,
    }


def actual_stats(n: int, rho: float, c: float, a: float) -> dict[str, float]:
    kernel = a * np.eye(n) + c * sine_toeplitz(n, rho)
    return dpp_entropy_stats(kernel)


def reproduce_n12_parity_decomposition() -> None:
    n = 12
    rho = 0.5
    c = 0.95
    a = 0.025
    q = sine_toeplitz(n, rho)
    even = np.arange(0, n, 2)
    odd = np.arange(1, n, 2)
    q_oo = q[np.ix_(odd, odd)]
    q_oe = q[np.ix_(odd, even)]
    q_eo = q[np.ix_(even, odd)]

    conditional_hessians = []
    conditional_entropies = []
    projection_defects = []
    for word in range(1 << len(even)):
        bits = (word >> np.arange(len(even))) & 1
        signs = np.diag(1 - 2 * bits)
        conditional = q_oo + 2 * q_oe @ signs @ q_eo
        stats = dpp_entropy_stats(a * np.eye(len(odd)) + c * conditional)
        conditional_hessians.append(stats["H2"])
        conditional_entropies.append(stats["H"])
        projection_defects.append(
            np.linalg.norm(conditional @ conditional - conditional, 2)
        )

    total = actual_stats(n, rho, c, a)
    even_entropy = len(even) * math.log(2)
    even_hessian = -4.0 * len(even)
    average_conditional_entropy = sum(conditional_entropies) / len(
        conditional_entropies
    )
    average_conditional_hessian = sum(conditional_hessians) / len(
        conditional_hessians
    )
    conditional_mutual_information = (
        total["H"] - even_entropy - average_conditional_entropy
    )
    conditional_mutual_information_hessian = (
        total["H2"] - even_hessian - average_conditional_hessian
    )
    b = (1 - c * c) / 4

    print("N12_TRUE_TOEPLITZ")
    print("H2_total", total["H2"])
    print("H2_even_iid", even_hessian)
    print("H2_average_conditioned_odd", average_conditional_hessian)
    print("H2_conditional_mutual_information", conditional_mutual_information_hessian)
    print("conditional_mutual_information", conditional_mutual_information)
    print("least_negative_conditioned_H2", max(conditional_hessians))
    print("observed_Fisher_J", total["J"])
    print("observed_Fisher_per_site", total["J"] / n)
    print("complete_data_Fisher_n_over_b", n / b)
    print("projection_defect_min", min(projection_defects))
    print("projection_defect_max", max(projection_defects))
    print("finite_compression_projection_defect", np.linalg.norm(q @ q - q, 2))
    print(
        "finite_QoeQeo_identity_defect",
        np.linalg.norm(q_oe @ q_eo - 0.25 * np.eye(len(odd)), 2),
    )


def report_midpoint_gamma() -> None:
    print("TRUE_TOEPLITZ_MIDPOINT_GAMMA_RHO_HALF_C_095")
    for n in range(1, 13):
        stats = actual_stats(n, 0.5, 0.95, 0.025)
        print(n, stats["F"] / n)


def cyclic_projection(n: int) -> np.ndarray:
    sites = np.arange(n)[:, None]
    frequencies = np.arange(n // 2)[None, :]
    fourier = np.exp(2j * np.pi * sites * frequencies / n) / math.sqrt(n)
    return fourier @ fourier.conj().T


def report_cyclic_gamma_and_fisher() -> None:
    c = 0.95
    a = 0.025
    b = (1 - c * c) / 4
    print("CYCLIC_PROJECTION_MIDPOINT_GAMMA_AND_FISHER")
    for n in (8, 10, 12, 14, 16):
        stats = dpp_entropy_stats(a * np.eye(n) + c * cyclic_projection(n))
        print(n, stats["F"] / n, stats["J"] / n, "complete_ceiling", 1 / b)


def superadditivity_probe() -> None:
    rhos = (0.2, 1 / 3, 0.5, 0.7)
    contrasts = (0.5, 0.8, 0.95)
    fractions = (0.02, 0.1, 0.3, 0.5, 0.7, 0.9, 0.98)
    smallest = (math.inf, None)
    violations = []

    for rho in rhos:
        for c in contrasts:
            for fraction in fractions:
                a = (1 - c) * fraction
                values = [0.0] + [
                    actual_stats(n, rho, c, a)["F"] for n in range(1, 11)
                ]
                for left in range(1, 10):
                    for right in range(1, 11 - left):
                        gap = values[left + right] - values[left] - values[right]
                        record = (rho, c, a, left, right)
                        if gap < smallest[0]:
                            smallest = (gap, record)
                        if gap < -1e-7:
                            violations.append((gap, record))

    print("SUPERADDITIVITY_PROBE_CASES", len(rhos) * len(contrasts) * len(fractions))
    print("SUPERADDITIVITY_PROBE_VIOLATIONS", len(violations))
    print("SUPERADDITIVITY_PROBE_SMALLEST_GAP", smallest)


if __name__ == "__main__":
    reproduce_n12_parity_decomposition()
    report_midpoint_gamma()
    report_cyclic_gamma_and_fisher()
    superadditivity_probe()
