"""Finite nonnormal subgroup sanity check for the new R12 interfaces.
This does not verify the infinite cyclic Fourier construction or prove R12.
"""
from fractions import Fraction as F
from itertools import permutations
from pathlib import Path
import hashlib,json
G=list(permutations(range(3)));e=(0,1,2)
prod=lambda p,q:tuple(p[q[i]] for i in range(3))
def inverse(p):return tuple(p.index(i) for i in range(3))
def conv(a,b):return {g:sum(a[h]*b[prod(inverse(h),g)] for h in G) for g in G}
def op(a):return [[a[prod(inverse(i),j)] for j in G] for i in G]
def mm(a,b):return [[sum(a[i][k]*b[k][j] for k in range(len(G))) for j in range(len(G))] for i in range(len(G))]
def rank(a):
    z=[row[:] for row in a];r=0
    for k in range(len(z[0])):
        p=next((i for i in range(r,len(z)) if z[i][k]),None)
        if p is None:continue
        z[r],z[p]=z[p],z[r];v=z[r][k];z[r]=[x/v for x in z[r]]
        for i in range(len(z)):
            if i!=r:
                v=z[i][k];z[i]=[x-v*y for x,y in zip(z[i],z[r])]
        r+=1
    return r
tau=(1,0,2);sig=(0,2,1);H={e,tau}
assert prod(prod(sig,tau),inverse(sig)) not in H
a={g:F(g in H,2) for g in G}
w={g:F(31*(g==e),32)+F(1,32)*(F(1,12)+F(g==sig,2)) for g in G}
assert sum(a.values())==sum(w.values())==1
assert all(w[g]>0 and w[g]==w[inverse(g)] for g in G)
A=op(a);W=op(w);v=conv(conv(a,w),a);V=op(v)
assert V==mm(mm(A,W),A)
assert mm(A,A)==A and mm(A,W)!=mm(W,A)
assert all(v[g]>0 and v[g]==v[inverse(g)] for g in G)
assert sum(v.values())==1
assert rank(A)==rank(V)==rank(mm(V,V))==3
# Right convolution by a preserves LEFT cosets, even when H is nonnormal.
for g in G:
    coset={prod(g,h) for h in H}
    for i in coset:
        for j in G:
            if j not in coset: assert not A[G.index(i)][G.index(j)]
# Coarse comparisons for the special finite test are exact.
lo=a[e]**2;upper=max(v[g]/w[g] for g in G)
assert all(v[g]>=lo*w[g] for g in G)
v3=conv(conv(v,v),v)
M=max(v3[g]/v[g] for g in G)
shifts={}
for h in G:
    shifts[str(h)]=str(max(v[prod(inverse(h),g)]/v[g] for g in G))
# Exact bookkeeping constants in the infinite proof.
assert 64**3*256*64==2**32
assert 64*4*64==16384
coeff_cases=0
for n in range(121):
    lhs=sum(F(1,(j+1)**2*(n-j+1)**2) for j in range(n+1))
    assert lhs<=F(16,(n+1)**2)
    coeff_cases+=1
formal=[1]
for n in range(1,21):
    formal.append(sum(2*formal[n-j] for j in range(1,n+1)))
    assert sum(formal)==3**n
r=Path(__file__).parent.parent
result={"status":"PASS_FINITE_NONNORMAL_CONVOLUTION_AND_BOOKKEEPING",
 "test_group":"S3; subgroup generated by a transposition, nonnormal",
 "A_W_noncommuting":True,"ranks_A_V_V2":[rank(A),rank(V),rank(mm(V,V))],
 "left_coset_invariance_checked":True,"sandwich_lower_factor":str(lo),
 "finite_test_upper_factor":str(upper),"finite_test_v3_factor":str(M),
 "finite_test_left_shifts":shifts,"coefficient_cases":coeff_cases,
 "count_ratio_cubed":"1/16","radius_ratio_cubed":"1/2",
 "statement_sha256":'bcb52e4e45939d40ebc0d1b3724cc0a030bee8dca781aff6fda48e045c45a7e4',
 "proof_sha256":'dd1fba05fa0cbe6dfd78d43e3263e2306e4f3754b3dae99b2094d7a2eed94f5d',
 "finite_sanity_only":True,"not_infinite_probability_proof_or_fresh_audit":True}
Path(__file__).with_suffix(".json").write_text(json.dumps(result,indent=2)+"\n",encoding="utf-8")
print(json.dumps({k:result[k] for k in ["status","A_W_noncommuting","ranks_A_V_V2","proof_sha256"]},indent=2))
